---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:7.2.0
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:7.2.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
